Repository QAPPA/qappa, pull requests merged in 2018-07, with the labels that each got.

#3 Authentication and authorization
  .gitignore
  config/custom-environment-variables.json
  config/default.json
  ormconfig.js
  package.json
  server/.env.example
  server/src/app.ts
  server/src/config/index.ts
  server/src/controllers/authenticationController.ts
  server/src/controllers/index.ts
  server/src/controllers/usersController.ts
  server/src/entities/User.ts
  server/src/index.ts
  server/src/middleware/auth.ts
  server/src/migrations/1532093001931-UpdateUser.ts
  tslint.json
Labels: core

#8 Implemented validation with Joi
  package.json
  server/src/controllers/authenticationController.ts
  server/src/controllers/usersController.ts
  server/src/utils/validations/user.ts
Labels: enhancement

#9 Basic frontend layout
  client/assets/css/main.sass
  client/components/Logo.vue
  client/components/SideMenu.vue
  client/components/TopMenu.vue
  client/layouts/auth.vue
  client/layouts/default.vue
  client/pages/index.vue
  client/pages/login/index.vue
  client/plugins/element-ui.js
  nuxt.config.js
  package.json
Labels: core

#11 [Frontend] Authorization and authentication
  client/components/TopMenu.vue
  client/layouts/auth.vue
  client/pages/index.vue
  client/pages/login/index.vue
  client/store/index.js
  config/default.json
  nuxt.config.js
  package.json
  server/src/app.ts
  server/src/controllers/authenticationController.ts
  server/src/controllers/index.ts
  server/src/controllers/usersController.ts
  server/src/index.ts
Labels: core

#10 [Testing] Setting up Jest + testing what we have
  .codeclimate.yml
  .travis.yml
  config/custom-environment-variables.json
  config/default.json
  config/test.json
  ormconfig.js
  package.json
  server/src/controllers/authenticationController.ts
  server/src/controllers/usersController.ts
  server/src/middleware/auth.ts
  server/tests/controllers/authenticationController.test.ts
  server/tests/controllers/usersController.test.ts
  server/tests/middleware/auth.test.ts
  server/tests/utils/validations/user.test.ts
  tsconfig.json
Labels: core, testing

#13 JWT Token validation with Joi
  server/src/controllers/authenticationController.ts
  server/src/controllers/usersController.ts
  server/src/middleware/auth.ts
  server/src/utils/validations/jwtToken.ts
  server/src/utils/validations/user.ts
  server/tests/controllers/usersController.test.ts
  server/tests/middleware/auth.test.ts
  server/tests/utils/validations/jwtToken.test.ts
Labels: enhancement, testing
